---
  
#- name:  Cambiar nombre de host
#  raw: "echo {{ hostname }} > /etc/hostname"

#- name:  Los cambios surten efecto
#  shell: "hostname {{ hostname }}"

#- name:  Establecer dns locales
#  shell: "if [ `grep '{{ ansible_ssh_host }} {{ hostname }}' /etc/hosts |wc -l` -eq 0 ]; then echo {{ ansible_ssh_host }} {{ hostname }} >> /etc/hosts; fi"
    
- name: Habilitar e iniciar firewall
  service: 
    name: firewalld 
    state: started 
    enabled: yes
  
- name: Permitir a Kubernetes manejar el trafico
  blockinfile:  
    create: yes
    path: /etc/sysctl.d/k8s.conf
    block: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1   

- name: Set modprobe
  shell: modprobe br_netfilter  

- name: Activar transparent masquerading
  firewalld: 
    masquerade: yes 
    permanent: true 
    state: enabled

- name: Reiniciar firewall
  command: firewall-cmd --reload 

- name: Aplicando cambios de configuracion
  command: sysctl --system

- name: Deshabilitar swap
  shell: |
         swapoff -a
         sed -i '/swap/d' /etc/fstab        

- name: Obtenemos CRI-O
  shell: |
         wget -O /etc/yum.repos.d/devel:kubic:libcontainers:stable.repo https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_8_Stream/devel:kubic:libcontainers:stable.repo 
         wget -O /etc/yum.repos.d/devel:kubic:libcontainers:stable:cri-o:1.23:1.23.1.repo https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:1.23:1.23.1/CentOS_8_Stream/devel:kubic:libcontainers:stable:cri-o:1.23:1.23.1.repo

- name: Configuramos los modulos del kernel necesarios para CRI-O
  blockinfile:
     create: yes
     path: "/etc/modules-load.d/crio.conf"
     block: |
            overlay
            br_netfilter
            EOF
            
- name: Instalamos CRI-O
  yum:
    name: cri-o
    state: latest

- name: Iniciar y habilitar servicio CRIO
  service:
    name: crio
    state: started
    enabled: yes

- name: Agregar repositorio de kubernetes
  blockinfile:
     create: yes
     path: /etc/yum.repos.d/kubernetes.repo
     block: |
            [kubernetes]
            baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
            enabled=1
            gpgcheck=1
            repo_gpgcheck=1
            gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg                       
            
- name:  Configurar fuente de kubernetes
  template: 
    src: /etc/yum.repos.d/kubernetes.repo 
    dest: /etc/yum.repos.d/kubernetes.repo
    owner: root 
    group: root
    mode: 0644
  become: true
  
- name: Instalar kubeadm, kubectl y kubelet
  command: 
    cmd: sudo dnf install -y kubelet kubeadm kubectl --disableexcludes=kubernetes

- name: Habilitar e iniciar servicio kubelet
  service:
    name: kubelet
    state: started
    enabled: yes    
