---

- name: Instalar paquetes NFS
  dnf:
    name: ['nfs-utils', 'net-tools']
    
- name: Arrancamos el servicio para nfs
  shell: systemctl enable nfs-server;systemctl start nfs-server
  
- name: Creamos directorio /srv/nfs
  file: 
    path: /srv/nfs 
    state: directory 
    mode: 777 
    owner: root 
    group: root
  
- name: Copiando a /etc/exports
  template: 
    src: exports.j2
    dest: /etc/exports 
    owner: root 
    group: root
    mode: 0644
  become: true
  
- name: Aplicar la nueva configuracion exportfs -r
  command: exportfs -r
  
- name: Aplicar la nueva configuracion exportfs -s
  command: exportfs -s

#- name: Instalar firewalld
#  dnf:
#    name: firewalld
#    state: latest

- name: Iniciar firewalld
  service:
    name: firewalld
    state: started
    enabled: yes
  become: yes

- name: Abrir puertos para que servicios sean accesibles
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  loop:
    - nfs
    - rpc-bind
    - mountd

- name: Reiniciar firewall
  command: firewall-cmd --reload